---
title: "getting-started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting-started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(scIso)
```

```{r load_data}
cell_types <- readRDS(gzcon(
  url("https://zenodo.org/records/17585277/files/Cell_type_annotation.rds")))

scmat_iso_url <- "https://zenodo.org/records/17585277/files/iso_matrix.zip"

tmp <- tempfile(fileext = ".zip")
download.file(scmat_iso_url, tmp)

unzip(tmp, exdir = tempdir())

scmat_iso <- Seurat::Read10X(data.dir = tempdir())
```

```{r init_sobj}
assay = "ISO"
iso_assay = Seurat::CreateAssayObject(counts = scmat_iso)
seurat_obj = Seurat::CreateSeuratObject(counts = iso_assay,
                                        assay = assay,
                                        project.name = sample_name)

seurat_obj[[paste0('log_nCount_', assay)]] = log(seurat_obj[[paste0('nCount_', assay)]])

seurat_obj
head(rownames(seurat_obj@assays$ISO$counts))
```


```{r normalization}
seurat_obj = Seurat::NormalizeData(seurat_obj,
                                   normalization.method = "LogNormalize",
                                   assay = "ISO",
                                   verbose=F)

seurat_obj = Seurat::FindVariableFeatures(seurat_obj,
                                          assay = "ISO",
                                          nfeatures = 3000,
                                          verbose=F)
seurat_obj
```

```{r filter_cells}
common_cells <- intersect(colnames(seurat_obj), names(cell_types))
seurat_obj <- seurat_obj[,common_cells]
```


```{r set_assay}
Seurat::DefaultAssay(seurat_obj) = "ISO"
ndims = 18
```

```{r dim_reduction}
seurat_obj = Seurat::ScaleData(seurat_obj,
                               features = rownames(seurat_obj), 
                               verbose = F)

var_features = Seurat::VariableFeatures(object = seurat_obj)

seurat_obj = Seurat::RunPCA(seurat_obj, 
                            features = var_features,
                            verbose = F, 
                            reduction.name = "RNA_pca", 
                            max_dims = 100)

seurat_obj = Seurat::RunUMAP(seurat_obj,
                             reduction = "RNA_pca",
                             dims = 1:ndims,
                             seed.use = 1337L,
                             verbose = F,
                             reduction.name = paste0("RNA_pca_", ndims, "_umap"))

seurat_obj = Seurat::RunTSNE(seurat_obj,
                             reduction = "RNA_pca",
                             dims = 1:ndims,
                             seed.use = 1337L,
                             verbose = F,
                             reduction.name = paste0("RNA_pca_", ndims, "_tsne"))

seurat_obj
```

```{r cell_annotation}
cell_types_named <- levels(cell_types)[cell_types]
names(cell_types_named) <- names(cell_types)

seurat_obj$cell_types <- NA_character_
seurat_obj$cell_types[common_cells] <- cell_types_named[common_cells]
```

```{r cell_viz, fig.height=3, fig.width=3}
proj <- "tsne"
Seurat::DimPlot(seurat_obj, reduction = paste0("RNA_pca_18_", proj), group.by = "cell_types") +
  ggplot2::labs(title = paste0(proj,"\n", "MPNST"),
                subtitle = paste0(ncol(seurat_obj), " cells")) +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 1,
                 plot.title = element_text(hjust = 0.5),
                 plot.subtitle = element_text(hjust = 0.5))
```

```{r compute_pi_mtx}
#pi_mtx <- scIso::computePIMatrix(seurat_obj, 
#                                 assay = "ISO",
#                                 slot = "count")
```

```{r load_pi_matrix}
url <- "https://zenodo.org/records/17585277/files/pi_mtx.rds"
tmp_rds <- tempfile(fileext = ".rds")

download.file(url, destfile = tmp_rds, mode = "wb", quiet = FALSE)

pi_mtx <- readRDS(tmp_rds)
```


```{r plot_pi}
scIso::plotPIPHI(pi_mat = pi_mtx,
                 iso_mat = seurat_obj@assays$ISO$counts,
                 min_gene_count = 3000
                 )
```

```{r fig.height=3, fig.width=10}
scIso::FeaturePlotPI(seurat_obj, 
                     name = "Srsf3", 
                     reduction = paste0("RNA_pca_18_", proj),
                     iso1 = "Srsf3..ENSMUST00000130216",
                     iso2 = "Srsf3..ENSMUST00000037776")
```

```{r}
sessionInfo()
```

